#!/usr/bin/env python3
"""Regenerate the copied-from-Gali artefacts in this repo.

Two outputs, both derived from the read-only Gali backend rather than retyped:

  lib/gali/constants.ts        the whole file
  docs/gali-ground-truth.md    only the regions between GENERATED markers -
                               the verbatim prompt blocks and the digest table

Everything else in the document is hand-written prose and is never touched.

Why this exists: the strings are ~21,000 characters of Hebrew clinical text. Hand
copying them is how a byte-level drift gets introduced, and the golden test only
catches drift after it has been committed. Answers Q3.

The Gali repos are READ-ONLY. This script opens files there for reading and
writes nothing, not even bytecode - see the sys.dont_write_bytecode line below,
which keeps __pycache__ out of a repo we are not allowed to touch.

Usage:
    uv run scripts/generate_gali_constants.py            # write both outputs
    uv run scripts/generate_gali_constants.py --check    # verify, write nothing
    uv run scripts/generate_gali_constants.py --gali-backend <path>

--check exits 1 on drift and prints which output disagrees, so it can be wired
into CI next to the four gates.
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import re
import sys
from typing import Callable

sys.dont_write_bytecode = True

DEFAULT_GALI_BACKEND = r"C:\Users\eb300\Desktop\Gali-AWS-backend"

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONSTANTS_PATH = os.path.join(REPO_ROOT, "lib", "gali", "constants.ts")
GROUND_TRUTH_PATH = os.path.join(REPO_ROOT, "docs", "gali-ground-truth.md")

# Provenance of the two source repos, recorded in the generated header.
BACKEND_COMMIT = "ab6a325 (2026-08-02)"
FRONTEND_COMMIT = "e950553 (2026-08-02)"

PART_ORDER = ("identity", "language", "voice", "rules", "formatAndFlags")

# Source lines for each part, for the document's per-part table.
PART_SOURCE_LINES = {
    "identity": "21-30",
    "language": "35-50",
    "voice": "55-98",
    "rules": "103-214",
    "formatAndFlags": "219-288",
}


class GaliSource:
    """The values production actually uses, after import-time substitution."""

    def __init__(self, backend_path: str) -> None:
        shared_root = os.path.join(backend_path, "shared")
        if not os.path.isdir(shared_root):
            raise SystemExit(f"No shared/ directory under {backend_path!r}")
        sys.path.insert(0, shared_root)
        from shared import prompt, redflag_classifier  # noqa: PLC0415

        self.parts: dict[str, str] = {
            "identity": prompt._IDENTITY,
            "language": prompt._LANGUAGE,
            "voice": prompt._VOICE,
            "rules": prompt._RULES,
            "formatAndFlags": prompt._FORMAT_AND_FLAGS,
        }
        self.rag_template: str = prompt.RAG_PROMPT_TEMPLATE
        self.system_prompt: str = prompt.SYSTEM_PROMPT
        self.classifier_prompt: str = redflag_classifier._SYSTEM_PROMPT


def ts_string(value: str) -> str:
    """A TypeScript double-quoted literal, byte-exact, Hebrew left as Hebrew."""
    return json.dumps(value, ensure_ascii=False)


def sha256(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def render_constants(src: GaliSource) -> str:
    """The whole of lib/gali/constants.ts."""
    header = f'''/**
 * Gali production constants, copied verbatim out of the read-only Gali repos.
 *
 * Every value here is a value to be COPIED, never chosen. `docs/gali-ground-truth.md`
 * records the provenance of each one — file and line — and lists explicitly what the
 * Gali repos do NOT state. Nothing in this module is inferred: a value the repos are
 * silent about is absent here rather than guessed.
 *
 * Sources, both read-only:
 *   backend   Gali-AWS-backend  @ {BACKEND_COMMIT}
 *   frontend  Gali-frontend     @ {FRONTEND_COMMIT}
 *
 * The prompt strings are the values AFTER the import-time phone-link substitution in
 * `shared/shared/prompt.py:394-404` — what production actually sends, not the
 * pre-substitution literals in the source file.
 *
 * `tests/gali/constants.golden.test.ts` pins every string in this module to the
 * SHA-256 digests recorded in `docs/gali-ground-truth.md`. Editing a value here
 * without re-reading Gali fails that test.
 *
 * GENERATED by scripts/generate_gali_constants.py. Do not hand-edit: run the
 * script, which reads the values back out of Gali.
 */

'''

    body: list[str] = []
    add = body.append

    add("/** AWS region. `shared/shared/config.py:14`, `scripts/ingest_kb.py:34`. */\n")
    add("export const GALI_REGION: string = 'eu-west-1';\n\n")

    add("/** Bedrock Knowledge Base id. `scripts/ingest_kb.py:32`, `samconfig.toml:10`. */\n")
    add("export const GALI_KNOWLEDGE_BASE_ID: string = 'CHAU7BWP4S';\n\n")

    add('''/**
 * The KB has two data source ids in the repo and they are not the same value. Both are
 * recorded, because the repo nowhere states that either supersedes the other.
 *
 * - `GALI_CUSTOM_DATA_SOURCE_ID` — the CUSTOM data source the markdown is pushed into
 *   with `IngestKnowledgeBaseDocuments` (`scripts/ingest_kb.py:33`,
 *   `scripts/kb_verify_reconstruct.py:26`).
 * - `GALI_SYNC_DATA_SOURCE_ID` — the `DataSourceId` the deployed sync Lambda calls
 *   `StartIngestionJob` against (`samconfig.toml:10` into `template.yaml:238`).
 */
''')
    add("export const GALI_CUSTOM_DATA_SOURCE_ID: string = 'PPIUPPCKNN';\n")
    add("export const GALI_SYNC_DATA_SOURCE_ID: string = 'FDN4IETFFW';\n\n")

    add("/** Data source type on the ingest path. `scripts/ingest_kb.py:222`. */\n")
    add("export const GALI_DATA_SOURCE_TYPE: string = 'CUSTOM';\n\n")

    add("/** Inference profile ids. `samconfig.toml:10`. */\n")
    add("export const GALI_PRIMARY_MODEL_ID: string = 'eu.anthropic.claude-sonnet-4-5-20250929-v1:0';\n")
    add("export const GALI_FALLBACK_MODEL_ID: string = 'eu.anthropic.claude-3-5-haiku-20241022-v1:0';\n\n")

    add('''/**
 * Retrieval and inference settings. All three are environment-variable defaults in
 * `shared/shared/config.py:27,34,35`; neither `template.yaml` nor `samconfig.toml`
 * overrides them, so these are the values production runs with.
 */
''')
    add("export const GALI_RETRIEVAL_TOP_K: number = 5;\n")
    add("export const GALI_GENERATION_MAX_TOKENS: number = 4096;\n")
    add("export const GALI_GENERATION_TEMPERATURE: number = 0.3;\n\n")

    add("/** Query transformation, chosen over Bedrock's default rewriter. `functions/chat/app.py:123`. */\n")
    add("export const GALI_QUERY_TRANSFORMATION_TYPE: string = 'QUERY_DECOMPOSITION';\n\n")

    add('''/**
 * Bedrock RetrieveAndGenerate hard-caps `textPromptTemplate` at 4096 characters and
 * requires the placeholder. Gali asserts both at import time
 * (`shared/shared/prompt.py:406-416`) — which is where ADR 0016 got the number.
 */
''')
    add("export const BEDROCK_RAG_PROMPT_TEMPLATE_LIMIT: number = 4096;\n")
    add("export const BEDROCK_SEARCH_RESULTS_PLACEHOLDER: string = '$search_results$';\n\n")

    add('''/**
 * THE LIVE PROMPT. The string production sends as `textPromptTemplate`
 * (`shared/shared/prompt.py:300-380`, sent at `functions/chat/app.py:127`). It is
 * hand-written and condensed — it is NOT the five parts joined.
 */
''')
    add("export const GALI_RAG_PROMPT_TEMPLATE: string = " + ts_string(src.rag_template) + ";\n\n")

    add('''/**
 * The five documentation parts (`shared/shared/prompt.py:21-288`) and the join that
 * builds `SYSTEM_PROMPT` at `shared/shared/prompt.py:293`. The separator is the empty
 * string: every part carries its own trailing newlines.
 *
 * The composed value is documentation in Gali, not the live prompt. At 11,492
 * characters it is nearly 3x the 4096 cap, so it could never be sent as one template.
 */
''')
    add("export type GaliSystemPromptPartName =\n")
    add("  | 'identity'\n  | 'language'\n  | 'voice'\n  | 'rules'\n  | 'formatAndFlags';\n\n")
    add("export const GALI_SYSTEM_PROMPT_PART_ORDER: readonly GaliSystemPromptPartName[] = [\n")
    for name in PART_ORDER:
        add(f"  '{name}',\n")
    add("] as const;\n\n")
    add("export const GALI_SYSTEM_PROMPT_SEPARATOR: string = '';\n\n")
    add("export const GALI_SYSTEM_PROMPT_PARTS: Readonly<Record<GaliSystemPromptPartName, string>> = {\n")
    for name in PART_ORDER:
        add(f"  {name}: {ts_string(src.parts[name])},\n")
    add("};\n\n")
    add('''/** The five parts joined the way Gali joins them. Equal to Gali's `SYSTEM_PROMPT`. */
export const GALI_SYSTEM_PROMPT: string = GALI_SYSTEM_PROMPT_PART_ORDER.map(
  (name) => GALI_SYSTEM_PROMPT_PARTS[name],
).join(GALI_SYSTEM_PROMPT_SEPARATOR);

''')

    add('''/**
 * The triage classifier: one Bedrock `Converse` call per turn, made BEFORE retrieval
 * (`shared/shared/redflag_classifier.py:213-247`, called at `functions/chat/app.py:416`).
 * Its prompt is locked at commit a635c2e (2026-07-05) — the last commit to touch that
 * file, and the commit the validation changelog names as the locked prompt.
 *
 * Any API error, empty response, or unparseable label resolves to `ER`, so a missed
 * classification can never suppress an escalation.
 */
''')
    add("export const GALI_TRIAGE_TIERS: readonly string[] = ['ER', 'CLARIFY_ER', 'SOFT', 'EXPLAIN'] as const;\n")
    add("export const GALI_TRIAGE_FAIL_SAFE_TIER: string = 'ER';\n")
    add("export const GALI_CLASSIFIER_MAX_TOKENS: number = 8;\n")
    add("export const GALI_CLASSIFIER_TEMPERATURE: number = 0;\n")
    add("export const GALI_CLASSIFIER_API: string = 'bedrock-runtime.Converse';\n")
    add("export const GALI_CLASSIFIER_PROMPT_LOCKED_AT: string = 'a635c2e';\n")
    add("export const GALI_CLASSIFIER_SYSTEM_PROMPT: string = " + ts_string(src.classifier_prompt) + ";\n\n")

    add('''/**
 * The chat-history table (`template.yaml:82-105`). The name is a CloudFormation `!Sub`
 * pattern, recorded verbatim. `samconfig.toml` sets no `Stage`, so the template default
 * `dev` applies, which matches `shared/shared/config.py:17`.
 */
''')
    add("export const GALI_CHAT_TABLE_NAME_PATTERN: string = 'gali-sessions-${Stage}';\n")
    add("export const GALI_CHAT_TABLE_STAGES: readonly string[] = ['dev', 'prod'] as const;\n")
    add("export const GALI_CHAT_TABLE_NAME_DEFAULT: string = 'gali-sessions-dev';\n\n")
    add('''export type GaliKeyType = 'HASH' | 'RANGE';
export type GaliAttributeType = 'S' | 'N';

export interface GaliKeySchemaEntry {
  readonly attributeName: string;
  readonly keyType: GaliKeyType;
  readonly attributeType: GaliAttributeType;
}

/** Composite key. A single-attribute key would not reproduce Gali. */
export const GALI_CHAT_TABLE_KEY_SCHEMA: readonly GaliKeySchemaEntry[] = [
  { attributeName: 'session_id', keyType: 'HASH', attributeType: 'S' },
  { attributeName: 'timestamp', keyType: 'RANGE', attributeType: 'N' },
] as const;

/** TTL attribute name: `ttl`, not `expires_at`. `template.yaml:104`. */
export const GALI_CHAT_TABLE_TTL_ATTRIBUTE: string = 'ttl';

/**
 * Expiry is the NEXT MIDNIGHT in Israel time, not a rolling 24 hours
 * (`shared/shared/history.py:87-91`, `shared/shared/time_utils.py:10`). A turn saved at
 * 23:50 expires ten minutes later, not the next evening.
 */
export const GALI_CHAT_TABLE_TTL_TIMEZONE: string = 'Asia/Jerusalem';
export const GALI_CHAT_TABLE_TTL_RULE: string =
  'next midnight in GALI_CHAT_TABLE_TTL_TIMEZONE';

''')

    add('''/**
 * The 9-key KB document metadata schema (`scripts/ingest_kb.py:41-44`), validated in
 * full before any network call (`scripts/ingest_kb.py:155-198`). This is the real
 * answer to the spec's "data entered in a defined structure, not free text".
 */
''')
    add(r'''export type GaliKbMetadataKey =
  | 'doc_type'
  | 'procedure_type'
  | 'gestational_age_max_weeks'
  | 'topic_tags'
  | 'contains_red_flags'
  | 'contains_emotional_support'
  | 'language'
  | 'source'
  | 'version';

/** Declaration order, as in `SCHEMA_KEYS`. */
export const GALI_KB_METADATA_KEYS: readonly GaliKbMetadataKey[] = [
  'doc_type',
  'procedure_type',
  'gestational_age_max_weeks',
  'topic_tags',
  'contains_red_flags',
  'contains_emotional_support',
  'language',
  'source',
  'version',
] as const;

/** The only optional key; omitted from the payload when absent. */
export const GALI_KB_METADATA_OPTIONAL_KEYS: readonly GaliKbMetadataKey[] = [
  'gestational_age_max_weeks',
] as const;

export type GaliInlineAttributeType = 'STRING' | 'NUMBER' | 'BOOLEAN' | 'STRING_LIST';

/** Bedrock `inlineAttributes` type per key (`scripts/ingest_kb.py:201-214`). */
export const GALI_KB_METADATA_ATTRIBUTE_TYPES: Readonly<
  Record<GaliKbMetadataKey, GaliInlineAttributeType>
> = {
  doc_type: 'STRING',
  procedure_type: 'STRING',
  gestational_age_max_weeks: 'NUMBER',
  topic_tags: 'STRING_LIST',
  contains_red_flags: 'BOOLEAN',
  contains_emotional_support: 'BOOLEAN',
  language: 'STRING',
  source: 'STRING',
  version: 'STRING',
};

/** Fixed values the validator enforces (`scripts/ingest_kb.py:37-39,177-186`). */
export const GALI_KB_METADATA_LANGUAGE: string = 'he';
export const GALI_KB_METADATA_SOURCE: string = 'Wolfson Medical Center';
export const GALI_KB_METADATA_VERSION_DEFAULT: string = '2026-06';
export const GALI_KB_METADATA_VERSION_PATTERN: RegExp = /^\d{4}-\d{2}$/;

/** `topic_tags`: 1-10 trimmed, non-empty, quote-free strings. */
export const GALI_KB_TOPIC_TAGS_MIN: number = 1;
export const GALI_KB_TOPIC_TAGS_MAX: number = 10;
''')

    return header + "".join(body)


def render_digest_table(src: GaliSource) -> str:
    """The golden table the constants test parses."""
    rows = ["| constant | chars | sha256 |", "| -------- | ----- | ------ |"]

    def row(name: str, value: str) -> str:
        return f"| `{name}` | {len(value)} | `{sha256(value)}` |"

    rows.append(row("GALI_RAG_PROMPT_TEMPLATE", src.rag_template))
    for name in PART_ORDER:
        rows.append(row(f"GALI_SYSTEM_PROMPT_PARTS.{name}", src.parts[name]))
    rows.append(row("GALI_SYSTEM_PROMPT", src.system_prompt))
    rows.append(row("GALI_CLASSIFIER_SYSTEM_PROMPT", src.classifier_prompt))
    return "\n".join(rows)


def render_rag_block(src: GaliSource) -> str:
    return "```text\n" + src.rag_template + "```"


def render_classifier_block(src: GaliSource) -> str:
    return "```text\n" + src.classifier_prompt + "\n```"


def render_part_table(src: GaliSource) -> str:
    """Per-part lengths and trailing-newline counts."""
    py_names = {
        "identity": "_IDENTITY",
        "language": "_LANGUAGE",
        "voice": "_VOICE",
        "rules": "_RULES",
        "formatAndFlags": "_FORMAT_AND_FLAGS",
    }
    rows = [
        "| part | Python name | source lines | chars | trailing newlines |",
        "| ---- | ----------- | ------------ | ----- | ----------------- |",
    ]
    for name in PART_ORDER:
        value = src.parts[name]
        trailing = len(value) - len(value.rstrip("\n"))
        rows.append(
            f"| `{name}` | `{py_names[name]}` | "
            f"`shared/shared/prompt.py:{PART_SOURCE_LINES[name]}` | "
            f"{len(value)} | {trailing} |"
        )
    return "\n".join(rows)


REGIONS: dict[str, Callable[[GaliSource], str]] = {
    "rag-prompt-template": render_rag_block,
    "classifier-system-prompt": render_classifier_block,
    "prompt-part-table": render_part_table,
    "digest-table": render_digest_table,
}


def replace_region(document: str, region: str, content: str) -> str:
    """Swap the body between the markers for `region`. Markers must exist."""
    begin = f"<!-- BEGIN GENERATED: {region} -->"
    end = f"<!-- END GENERATED: {region} -->"
    pattern = re.compile(
        re.escape(begin) + r"\n.*?\n" + re.escape(end),
        re.DOTALL,
    )
    replacement = f"{begin}\n{content}\n{end}"
    updated, count = pattern.subn(lambda _match: replacement, document)
    if count != 1:
        raise SystemExit(
            f"Expected exactly one '{region}' GENERATED region in "
            f"{GROUND_TRUTH_PATH}, found {count}. Add the markers first."
        )
    return updated


def read_text(path: str) -> str:
    with io.open(path, encoding="utf-8", newline="") as handle:
        return handle.read().replace("\r\n", "\n")


def write_text(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--gali-backend",
        default=DEFAULT_GALI_BACKEND,
        help="Path to the read-only Gali-AWS-backend checkout",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the outputs match Gali; write nothing; exit 1 on drift",
    )
    args = parser.parse_args()

    src = GaliSource(args.gali_backend)

    constants = render_constants(src)
    document = read_text(GROUND_TRUTH_PATH)
    for region, render in REGIONS.items():
        document = replace_region(document, region, render(src))

    outputs = ((CONSTANTS_PATH, constants), (GROUND_TRUTH_PATH, document))

    if args.check:
        drifted = [path for path, expected in outputs if read_text(path) != expected]
        for path in drifted:
            print(f"DRIFT: {os.path.relpath(path, REPO_ROOT)}", file=sys.stderr)
        if drifted:
            print(
                "Run scripts/generate_gali_constants.py to regenerate.",
                file=sys.stderr,
            )
            return 1
        print("Both outputs match the Gali source.", file=sys.stderr)
        return 0

    for path, content in outputs:
        write_text(path, content)
        print(f"wrote {os.path.relpath(path, REPO_ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
